### ISSUE TITLE
dwm_mpd? :)

### ISSUE THREAD

**Issue by kronikpillow** [joestandring/dwm-bar#1]
not a pro at shell scripting :) but I am eager for the dwm_mpd function, any chance it will come out anytime soon?

**Comment by joestandring** [comment]
I've been pretty busy at the moment but its next on my list. Now I have some time to work on it it should be done pretty soon :)

**Comment by joestandring** [comment]
Just added dwm_mpc that takes metadata and status from mpc and formats it like dwm_cmus. Should work with other mpd clients as long as mpc is installed :)
