### ISSUE TITLE
Read/write disk speed functions

### ISSUE THREAD

**Issue by basilroztor95** [joestandring/dwm-bar#12]
It would be cool if there was a dwm_disk_io function from /sys/class/block/*/stat. In the form of disk read/write speed. Read is the third and write is the seventh columns.

I tried to write myself, but it didn't work (

**Comment by joestandring** [comment]
Looking into this now, there was a bit of a delay because I was moving and having internet issues. I'll see if I can throw something together, thanks for the idea!

**Comment by joestandring** [comment]
/sys/class/block/*/stat only displays the number of reads/writes the disk has performed and not the speed. To get that you would require utilities like hdparm/sdparm that are too resource intensive to be responsive on a status bar.
