### ISSUE TITLE
Parallelizing non-local processes

### ISSUE THREAD

**Issue by Vincenzo-Petrolo** [joestandring/dwm-bar#15]
# Parallelizing internet related tasks
I'm opening this issue because i wanted to make a pull request, with some change to the code, in order to improve this bar that is amazing.
## Why an issue
Well, if you don't have a powerful connection, that's my case, you might have noticed that when getting weather forecast, as an example, the bar stops working, and all the real time data,such as battery percentage or time, that i need become useless.
## How to solve this
I solved it on my machine, by creating a separation in modules:
+ Local modules : All that modules that work in your local area network, such as date, battery, solar panels,backlight,audio,resources...
+ Non-local modules : All that modules that make use of the world area network, such as weather forecast, external ip...

As a solution i would not use local variable for **non-local modules**, but environment variables named as follows: ```__DWM_BAR_XXXXX_MODULE__```

And here is the weather module code: (Note that 2 lines only has changed:
```dwm_weather() {
      LOCATION=Modica

      printf "%s" "$SEP1"
      if [ "$IDENTIFIER" = "unicode" ]; then
>>        export __DWM_BAR_WEATHER_MODULE__="${SEP1} $(curl -s wttr.in/$LOCAT
  ION?format=1) ${SEP2}"
      #   printf "%s" "$(curl -s wttr.in/$LOCATION?format=1)"
      else
>>        export __DWM_BAR_WEATHER_MODULE__="${SEP1}WEA $(curl -s wttr.in/$LO
  CATION?format=1 | grep -o "[0-9].*") ${SEP2}"
      #   printf "WEA %s" "$(curl -s wttr.in/$LOCATION?format=1 | grep -o "[0
  -9].*")"
      fi
  }

  dwm_weather
```

While in the dwm_bar.sh i would add a function named parallelize()  that calls the non-local modules, note that this runs on background so it doesn't stops the other local modules which are running.
Now i describe its behaviour, at the first time, if the __DWM_BAR_WEATHER_MODULE__ has not been set, it simply returns an error and doesn't add it to the bar, but when it finishes fetching it, then it will update the environment variable and the next second it will show up in the bar.

```
parallelize() {
        while true
        do
                dwm_weather
        done
}

# call to parallelize
parallelize &


# Update dwm status bar every second
while true
do

    # Append results of each func one by one to a string
    dispstr=""
    dispstr="$dispstr$(dwm_resources)"
    dispstr="$dispstr$(dwm_battery)"
    dispstr="$dispstr$(dwm_backlight)"
    dispstr="$dispstr$(dwm_pulse)"
    dispstr="$dispstr${__DWM_BAR_WEATHER_MODULE__}"
    dispstr="$dispstr$(dwm_date)"

    xsetroot -name "$dispstr"
    sleep 1

done
```

## Conclusion
By applying this to all modules we can achieve real-time status bar without stopping it in case of slow internet connection speed.

**Comment by joestandring** [comment]
Hi, sorry for leaving this so late. I began to work on this however other things got in the way. I have been noticing freezes when using "heavier" modules like weather and spotify too so I would like to implement this.

**Comment by Vincenzo-Petrolo** [comment]
We can work on it together, i managed to solve the problem only for the weather module and the solar panel modules bc i only use them. But we should do it for every module

**Comment by joestandring** [comment]
Yeah, think thats a worthwhile improvement. If you manage to make any I'd be more than happy to merge them, I'll try to work on some other ones too.

**Comment by joestandring** [comment]
I have altered both dwm_weather and dwm_networkmanager to use your method. I havent been running into any issues testing this. I'd like to apologize for this taking so long too, I have been busy with other projects and university. Thanks again for the issue, closing now.

**Comment by Vincenzo-Petrolo** [comment]
Hi there, sorry for the late response, I'm not using dwm since a while, and i don't plan to come back to it soon. Anyway thanks for taking into account my issue. Best luck :)
