### ISSUE TITLE
weird text error in cmus plugin

### ISSUE THREAD

**Issue by twl-surrogate** [joestandring/dwm-bar#23]
this only happens on specific artists for some reason, but it shows the word "tag artistsort", the artists name twice, then the title track and everything else.

![Screenshot from 2021-04-24 11-03-19](https://user-images.githubusercontent.com/69609303/115964998-b6244700-a4ec-11eb-9df5-b36ea8358fed.png)

**Comment by joestandring** [comment]
Hi, is this using dwm_spotify.sh or dwm_cmus.sh?

**Comment by twl-surrogate** [comment]
yes, this is dwm_cmus.sh, though i do have both loaded

```
. "$DIR/bar-functions/dwm_cmus.sh"
. "$DIR/bar-functions/dwm_spotify.sh"
. "$DIR/bar-functions/dwm_battery.sh"
. "$DIR/bar-functions/dwm_date.sh"
. "$DIR/bar-functions/dwm_resources.sh"
```

**Comment by worbgge** [comment]
Hello, i know the reason why and am trying to find a solution, basically in /dwm-bars/bar-functions/dwm_cmus.sh how it gets the artist is doing 
`ARTIST=$(cmus-remote -Q | grep -a '^tag artist' | awk '{gsub("tag artist ", "");print}')`
if you use something like musicbrainz picard then it will also make a tag called artistssort, if you run cmus-remote -Q you should see the two of them so the grep is grepping both artist and artistsort and awk isn't getting rid of artistsort. any help on a solution on this would be nice (i am not the best at bash scripting)
