### ISSUE TITLE
status bar is not showing 

### ISSUE THREAD

**Issue by shashank-16** [joestandring/dwm-bar#30]
after applying the dwm barpadding patch status has been hidden but dwm-bar.sh is running but showing on the bar 

![dwm-bar](https://user-images.githubusercontent.com/73840885/151051931-c3871a5b-c1f6-46a4-bcf9-83ae8a5fc861.png)

**Comment by joestandring** [comment]
(Sorry for the delay, I have been unable to test recently)
Just tried with a fresh dwm config with barpadding 2021-10-20 patched and it appears to display for me. Could you show me the output of running dwm_bar.sh in the terminal? It's possible you are missing some dependencies for certain functions.
