### ISSUE TITLE
Crash in Ubuntu20.04

### ISSUE THREAD

**Issue by leitro** [joestandring/dwm-bar#8]
Hi! I'm new to dwm and have a problem in running dwm-bar. What I did:

1. Install dwm using apt
2. log out gnome and log in dwm
3. run ./dwm_bar.sh

Then, it just crashed and took me back to the login screen. How to solve it? Cheers!

**Comment by joestandring** [comment]
Have you made sure all the dependencies are installed for the functions themselves? I don't have an Ubuntu install at hand to test this but I'll try to give you a few suggestions.

**Comment by leitro** [comment]
> Have you made sure all the dependencies are installed for the functions themselves? I don't have an Ubuntu install at hand to test this but I'll try to give you a few suggestions.

I would appreciate any suggestion! As the crash was so quick that I cannot see what happened, I switched back to gnome and ran the shell script, that's what I got:

```
./dwm-bar/dwm_bar.sh: 10: /home/oo/dwm-bar/bar-functions/dwm_transmission.sh: transmission-remote: not found
[]
sysctl: cannot stat /proc/sys/hw/sensors/cpu0/temp0: No such file or directory
[💻 MEM 3,9Gi/7,7Gi CPU  STO /: ]
[🔋 95% Unknown]
ls: cannot access '/path/to/inbox': No such file or directory
[📪 0]
./dwm-bar/dwm_bar.sh: 10: /home/oo/dwm-bar/bar-functions/dwm_backlight.sh: xbacklight: not found
[☀ 0]
[🔊 76%]
./dwm-bar/dwm_bar.sh: 10: /home/oo/dwm-bar/bar-functions/dwm_pulse.sh: pamixer: not found
[./dwm-bar/dwm_bar.sh: 14: [: Illegal number: 
./dwm-bar/dwm_bar.sh: 16: [: Illegal number: 
./dwm-bar/dwm_bar.sh: 18: [: Illegal number: 
🔊 %]
[☀️ +20°C]
[🌐 MiFibra-1B91 192.168.1.28/24 | [masking haha]]
[⌨ us,us]
head: cannot open '/home/oo/.calcurse/apts' for reading: No such file or directory
[📆 dom 24-05-20 23:57:17]
[🌐 ./dwm-bar/dwm_bar.sh: 20: /home/oo/dwm-bar/bar-functions/dwm_connman.sh: connmanctl: not found
OFFLINE]
[⏱ 1.20 1.56 1.14]
./dwm-bar/dwm_bar.sh: 20: connmanctl: not found
./dwm-bar/dwm_bar.sh: 49: dwm_alarm.sh: not found
./dwm-bar/dwm_bar.sh: 10: transmission-remote: not found
sysctl: cannot stat /proc/sys/hw/sensors/cpu0/temp0: No such file or directory
ls: cannot access '/path/to/inbox': No such file or directory
./dwm-bar/dwm_bar.sh: 10: xbacklight: not found
./dwm-bar/dwm_bar.sh: 10: pamixer: not found
./dwm-bar/dwm_bar.sh: 14: [: Illegal number: 
./dwm-bar/dwm_bar.sh: 16: [: Illegal number: 
./dwm-bar/dwm_bar.sh: 18: [: Illegal number:
```

I'm not sure if it makes sense to run the script under gnome... Any idea?
BTW, which linux distro do you use?

**Comment by joestandring** [comment]
Thanks for the logs, there shouldnt be a problem with gnome installed as long as you run the script inside dwm. From the logs it seems like you are missing a few dependencies for some functions namely transmission, xbacklight, pamixer, calcurse and a few more. If you dont need to use a certain function (such as backlight or pulse audio volume) you can comment out/remove the lines the dwm_bar.sh script for example:
```
# Import the modules
. "$DIR/bar-functions/dwm_countdown.sh"
. "$DIR/bar-functions/dwm_alarm.sh"
. "$DIR/bar-functions/dwm_transmission.sh"
#. "$DIR/bar-functions/dwm_cmus.sh"
. "$DIR/bar-functions/dwm_mpc.sh"
#. "$DIR/bar-functions/dwm_spotify.sh"
. "$DIR/bar-functions/dwm_resources.sh"
. "$DIR/bar-functions/dwm_battery.sh"
. "$DIR/bar-functions/dwm_mail.sh"
#. "$DIR/bar-functions/dwm_backlight.sh"
. "$DIR/bar-functions/dwm_alsa.sh"
#. "$DIR/bar-functions/dwm_pulse.sh"
. "$DIR/bar-functions/dwm_weather.sh"
. "$DIR/bar-functions/dwm_vpn.sh"
. "$DIR/bar-functions/dwm_networkmanager.sh"
. "$DIR/bar-functions/dwm_keyboard.sh"
#. "$DIR/bar-functions/dwm_ccurse.sh"
. "$DIR/bar-functions/dwm_date.sh"
. "$DIR/bar-functions/dwm_connman.sh"
. "$DIR/bar-functions/dwm_loadavg.sh"
```
or install the optional dependencies for those functions listen in the README.
Hopefully that was some help!

**Comment by joestandring** [comment]
Closing this as it's been a week.
