### ISSUE TITLE
Weather service wttr.in ran out of requests ...

### ISSUE THREAD

**Issue by Ahacad** [joestandring/dwm-bar#9]
The weather service `wttr.in` ran out of requests just now (for today).
```
Sorry, we processed more than 1M requests today and we ran out of our datasource capacity.
We hope to solve the problem as soon as possible, so you can enjoy
your favourite weather service 24x365 even if it rains or snows.

We will solve the problem as soon as possible.
follow @igor_chubin for the updates. 
```
You might want to remind people to slow down requests a bit, or add some reminds in README, if they meet unexpected problems on the weather module.

**Comment by joestandring** [comment]
To be honest I've been looking into using another weather service as wttr.in isn't really built for how it's being used in the module. I'm going to add a reminder to the README until (hopefully) when I have time I find a better solution.
